---
title: "Tissue-partitioned BMI instrument procedure"
author: "Nick Sunderland"
date: "2025-01-10"
execute:
  fig-path: "posts/2025-01-10-tissue-partitioned-mvmr/" 
---

## Motivation
What does the weighting by PPH4 do to tissue partitioned BMI instruments? Let's simulate some tissue partitioned BMI MR results.

```{r load-packages}
#| warning: false
library(data.table)
library(ggplot2)
library(genepi.utils)
```


## BMI data
First load the BMI GWAS.

```{r}
#| message: false
#| eval: true

bmi <- readRDS(file.path(TPMR_DIR, "output", "tmp_objects", "obj_bmi.RDS"))
bmi
```

<!-- ## Heart failure data -->
<!-- Load the heart failure GWAS. -->

<!-- ```{r, message=FALSE, eval=F} -->
<!-- hf <- readRDS(file.path(dir, "tmp_objects", "obj_hf_allcause.RDS")) -->
<!-- hf -->
<!-- ``` -->

<!-- ## Harmonise the datasets -->
<!-- ```{r, message=FALSE, eval=F} -->
<!-- h   <- MR(bmi, hf) -->
<!-- h   <- clump_mr(h, p1=5e-8, r2=0.001, kb=10000, plink_ref=plink_ref) -->
<!-- dat <- as.data.table(h)[index_snp==TRUE] -->
<!-- saveRDS(dat, "~/Desktop/tpmr_simulation.RDS") -->
<!-- ``` -->
<!-- ```{r, include=FALSE} -->
<!-- dat <- readRDS("~/Desktop/tpmr_simulation.RDS") -->
<!-- ``` -->

<!-- ## Plot the variants -->
<!-- ```{r, warning=FALSE, message=FALSE} -->
<!-- p <- ggplot(dat, aes(x=bx, y=by, xmin=bx-bxse*1.96, xmax=bx+bxse*1.96, ymin=by-byse*1.96, ymax=by+byse*1.96)) + -->
<!--   geom_errorbar(color="lightgrey") + -->
<!--   geom_errorbarh(color="lightgray") + -->
<!--   geom_point() + -->
<!--   geom_smooth(method="lm", se=F) -->
<!-- p -->
<!-- ``` -->

<!-- ## Randomly select a proportion of the variants -->
<!-- ```{r, warning=FALSE, message=FALSE} -->
<!-- set.seed(123) -->
<!-- proportion <- 0.2 -->
<!-- dat[, selected := sample(c(TRUE, FALSE), .N, replace = TRUE, prob = c(proportion, 1 - proportion))] -->

<!-- p <- ggplot(dat, aes(x=bx, y=by, xmin=bx-bxse*1.96, xmax=bx+bxse*1.96, ymin=by-byse*1.96, ymax=by+byse*1.96, color=selected)) + -->
<!--   geom_errorbar(color="lightgrey") + -->
<!--   geom_errorbarh(color="lightgray") + -->
<!--   geom_point() + -->
<!--   geom_smooth(method="lm", se=F) -->
<!-- p -->
<!-- ``` -->

<!-- ## Create different distributions of PPH4 weights -->
<!-- ```{r, warning=FALSE, message=FALSE} -->
<!-- min_pph4 <- 0.8 -->
<!-- weighted <- lapply(1:20, function(dist_shape) { -->
<!--   d <- copy(dat[selected==TRUE]) -->
<!--   d[, `:=`(pph4  = min_pph4 + (1.0 - min_pph4) * rbeta(.N, shape1 = 5, shape2 = dist_shape), -->
<!--            shape = dist_shape)] -->
<!-- }) |> rbindlist() -->
<!-- weighted[, mean_pph4 := round(mean(pph4),3), by=.(shape)] -->
<!-- weighted[, mean_pph4 := factor(mean_pph4, levels = unique(mean_pph4))] -->

<!-- p <- ggplot(weighted, aes(x=pph4, fill=mean_pph4)) + -->
<!--   geom_density(alpha=0.2) -->
<!-- p -->
<!-- ``` -->

<!-- ## Apply the weightings -->
<!-- ```{r, warning=FALSE, message=FALSE} -->
<!-- weighted[, bx_weighted := bx*pph4] -->

<!-- p <- ggplot(weighted, aes(x=bx_weighted, y=by, xmin=bx-bxse*1.96, xmax=bx+bxse*1.96, ymin=by-byse*1.96, ymax=by+byse*1.96, color=mean_pph4)) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method="lm", se=F) -->
<!-- p -->
<!-- ``` -->

<!-- ## IVW regression by different PPH4 weighting distributions -->
<!-- ```{r, warning=FALSE, message=FALSE} -->
<!-- ivw_result <- weighted[, { -->
<!--   weights <- 1 / (byse^2) -->
<!--   model   <- lm(by ~ bx_weighted - 0, weights = weights) -->
<!--   coef_summary <- summary(model)$coefficients -->
<!--   slope        <- coef_summary["bx_weighted", "Estimate"] -->
<!--   se_slope     <- coef_summary["bx_weighted", "Std. Error"] -->
<!--   list(slope = slope, se = se_slope) -->
<!-- }, by = mean_pph4] -->

<!-- ivw_result[, mean_pph4 := as.numeric(as.character(mean_pph4))] -->

<!-- p <- ggplot(ivw_result, aes(x=mean_pph4, y=slope, ymin=slope-1.96*se, ymax=slope+1.96*se, color=mean_pph4, group=1)) + -->
<!--   geom_errorbar() + -->
<!--   geom_point() + -->
<!--   labs(y="IVW MR estimate") + -->
<!--   guides(color = "none") -->
<!-- p -->
<!-- ``` -->

<!-- ## Interpretation -->
<!-- Lower colocalisation evidence (lower PPH4) for any given instrument set leads to increasing MR estimate for the effect of BMI on an outcome due to greater down weighting of the BMI betas and consequent increase in the regression slope. -->