name: Quarto Render

on:
  push:
    branches:
      - main  # Adjust to your default branch if different
  pull_request:
    branches:
      - main  # Adjust to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Quarto
    - name: Set up Quarto
      uses: quarto-dev/quarto-action@v2

    # Render the Quarto project
    - name: Render Quarto Project
      run: quarto render

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
